# Site settings
title: Jericho
email: ekt.batey@gmail.com
description: A project on archaeology in the Holy Land
baseurl: "/jericho" # the subpath of your site, e.g. /blog/
url: "http://bateyt.github.io" # the base hostname & protocol for your site
twitter_username: bateytk
github_username:  bateyt


# Build settings
markdown: kramdown

# Syntax highlighter
highlighter: pygments

# Set encoding
encoding: utf-8